### ISSUE TITLE
Short example

### ISSUE THREAD

**Issue by tatecarson** [musikata/guido.js#31]
Hi, 

I'm a little new to javascript but I'd like to explore this package and see what I can do. Is there any small example so i can see how all these files are supposed to work together? I don't see any html file or know what to include there, a little confused. Any help would be appreciated. 

thanks

**Comment by adorsk** [comment]
Hi,

I'm glad to hear you're interested in music & coding.

This is a project that I started, but didn't continue. I don't recommend going forward with it.

However, if you are interested in music notation, I can recommend a few things to check out:
1. http://web.mit.edu/music21/
2. The original Guido engine: http://guidolib.sourceforge.net/
